name: Generate contribution snake
on:
  schedule:
    - cron: "0 0 * * *" # runs once a day
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: malik8154
          outputs: |
            output/snake.svg

      - name: Push generated files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update snake.svg"
